#!/usr/bin/env python3
"""build-catalog.py — generate the complete agent roster from source frontmatter.

Why: README.md curates highlight tables by hand, and by construction it cannot keep
up with the catalog (the unified import added 186 agents that no README table
lists). CATALOG.md is the complete, generated roster: every frontmatter agent in
every division from divisions.json, plus the NEXUS runbooks from
strategy/runbooks.json. It never drifts because it is never edited by hand.

Usage:
  python3 scripts/build-catalog.py            # write CATALOG.md
  python3 scripts/build-catalog.py --check    # exit 1 if CATALOG.md is stale (CI)
  python3 scripts/build-catalog.py --json OUT # also write a machine-readable catalog
                                              # (includes each agent's body) for apps

Only the Python standard library is used; frontmatter is parsed with the same
first-`---`-block contract as scripts/lint-agents.sh.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "CATALOG.md"


def parse_agent(path: Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    fm_raw, body = text[4:end], text[end + 5 :]
    fm = {}
    key = None
    for line in fm_raw.splitlines():
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if m:
            key = m.group(1)
            fm[key] = m.group(2).strip()
        elif key and line[:1] in (" ", "\t") and line.strip():
            # Plain scalars may continue on indented lines; YAML folds them with single
            # spaces (same rule as get_field in scripts/lib.sh).
            fm[key] = (fm[key] + " " + line.strip()).strip()
    for k, val in fm.items():
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            fm[k] = val[1:-1]
    if not fm.get("name"):
        return None
    return fm, body


def collect():
    divisions = json.loads((ROOT / "divisions.json").read_text(encoding="utf-8"))["divisions"]
    agents = []
    for div, meta in divisions.items():
        for path in sorted((ROOT / div).rglob("*.md")):
            parsed = parse_agent(path)
            if not parsed:
                continue
            fm, body = parsed
            rel = path.relative_to(ROOT).as_posix()
            agents.append(
                {
                    "slug": path.stem,
                    "path": rel,
                    "division": div,
                    "name": fm["name"],
                    "description": fm.get("description", ""),
                    "emoji": fm.get("emoji", ""),
                    "vibe": fm.get("vibe", ""),
                    "color": fm.get("color", ""),
                    "source": "openclaw-community" if fm.get("source_repo") else "agency",
                    "body": body,
                }
            )
    runbooks = json.loads((ROOT / "strategy" / "runbooks.json").read_text(encoding="utf-8"))["runbooks"]
    return divisions, agents, runbooks


def md_cell(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(divisions, agents, runbooks) -> str:
    by_div = {d: [a for a in agents if a["division"] == d] for d in divisions}
    imports = sum(1 for a in agents if a["source"] == "openclaw-community")
    out = [
        "# Agency Catalog",
        "",
        "> Generated by `scripts/build-catalog.py` from agent frontmatter, `divisions.json`, and",
        "> `strategy/runbooks.json`. Do not edit by hand — run `python3 scripts/build-catalog.py`.",
        "",
        f"**{len(agents)} agents** across **{len(divisions)} divisions** "
        f"({imports} normalized from the OpenClaw community source) and **{len(runbooks)} NEXUS runbooks**.",
        "",
        "## Divisions",
        "",
        "| Division | Agents |",
        "|---|---:|",
    ]
    for d, meta in divisions.items():
        anchor = re.sub(r"[^a-z0-9 -]", "", meta["label"].lower()).replace(" ", "-")
        out.append(f"| [{meta['label']}](#{anchor}) | {len(by_div[d])} |")
    out += ["", "## Runbooks", "", "| Runbook | Mode | Duration | Agents | Document |", "|---|---|---|---:|---|"]
    for rb in runbooks:
        n = len({s for g in rb["roster"] for s in g["agents"]})
        out.append(
            f"| **{md_cell(rb['title'])}** — {md_cell(rb.get('summary', ''))} | {rb['mode']} | "
            f"{md_cell(rb.get('duration', ''))} | {n} | [{rb['doc']}]({rb['doc']}) |"
        )
    for d, meta in divisions.items():
        out += ["", f"## {meta['label']}", "", "| Agent | Description |", "|---|---|"]
        for a in sorted(by_div[d], key=lambda a: a["name"].lower()):
            label = f"{a['emoji']} {a['name']}".strip()
            out.append(f"| [{md_cell(label)}]({a['path']}) | {md_cell(a['description'])} |")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if CATALOG.md is out of date")
    ap.add_argument("--json", metavar="OUT", help="also write a machine-readable catalog to OUT")
    args = ap.parse_args()

    divisions, agents, runbooks = collect()
    names = {}
    for a in agents:
        names.setdefault(a["name"].lower(), []).append(a["path"])
    dupes = {n: p for n, p in names.items() if len(p) > 1}
    if dupes:
        for n, p in dupes.items():
            print(f"ERROR duplicate agent name '{n}': {', '.join(p)}")
        return 1

    rendered = render_markdown(divisions, agents, runbooks)
    if args.check:
        current = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
        if current != rendered:
            print("FAILED: CATALOG.md is stale. Run: python3 scripts/build-catalog.py")
            return 1
        print(f"PASSED: CATALOG.md is current ({len(agents)} agents, {len(runbooks)} runbooks).")
    else:
        CATALOG.write_text(rendered, encoding="utf-8")
        print(f"Wrote CATALOG.md ({len(agents)} agents, {len(divisions)} divisions, {len(runbooks)} runbooks).")

    if args.json:
        payload = {
            "divisions": divisions,
            "runbooks": runbooks,
            "agents": agents,
        }
        Path(args.json).write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
        print(f"Wrote {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
