#!/usr/bin/env bash
# Thin conversion orchestrator. The renderer remains in convert-engine.sh;
# canonical single-tool refreshes use granular integration state.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENGINE="$SCRIPT_DIR/convert-engine.sh"
STATE="$SCRIPT_DIR/integration-state.py"
REGISTRY="$SCRIPT_DIR/registry.py"

# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

command -v python3 >/dev/null 2>&1 || {
  echo "ERROR: python3 is required for the tool registry" >&2
  exit 1
}

CONVERTED_TOOLS=()
while IFS= read -r tool; do
  [[ -n "$tool" ]] && CONVERTED_TOOLS+=("$tool")
done < <(python3 "$REGISTRY" tools "$REPO_ROOT/tools.json" --converted)
[[ ${#CONVERTED_TOOLS[@]} -gt 0 ]] || {
  echo "ERROR: no converted tools found in tools.json" >&2
  exit 1
}

write_aider_index() {
  local out_dir="$1"
  local dest="$out_dir/aider/CONVENTIONS.md"
  local divisions dir dirpath file name description source division

  mkdir -p "$(dirname "$dest")"
  cat > "$dest" <<'HEREDOC'
# The Agency — AI Agent Conventions
#
# The roster of specialized AI agents from The Agency
# (https://github.com/msitarzewski/agency-agents): each one's name, what it is
# for, and where its full instructions live.
#
# Aider keeps a conventions file in context for the whole session, so this is an
# index and not the agents themselves. Inlining every body would make this file
# too large for routine requests.
#
# To use an agent:
#   1. Name it in your prompt — "Use the Frontend Developer agent to review
#      this component." The description below is usually enough for that.
#   2. For its full instructions, pull the agent file into the session:
#        /read-only /path/to/agency-agents/engineering/engineering-frontend-developer.md
#
# Paths below are relative to an agency-agents checkout.
#
# Generated by scripts/convert.sh — do not edit manually.

HEREDOC

  divisions="$(python3 "$REGISTRY" divisions "$REPO_ROOT/divisions.json")" || return 1
  while IFS= read -r dir; do
    [[ -n "$dir" ]] || continue
    dirpath="$REPO_ROOT/$dir"
    [[ -d "$dirpath" ]] || continue
    while IFS= read -r -d '' file; do
      is_agent_file "$file" || continue
      name="$(get_field "name" "$file")"
      [[ -n "$name" ]] || continue
      description="$(get_field "description" "$file")"
      source="${file#"$REPO_ROOT"/}"
      division="${source%%/*}"
      cat >> "$dest" <<HEREDOC

---

## ${name}

> ${description}

Division: ${division}
Full instructions: ${source}
HEREDOC
    done < <(find "$dirpath" -name "*.md" -type f -print0 | sort -z)
  done <<< "$divisions"
}

requested_tool="all"
out_dir="$REPO_ROOT/integrations"
args=("$@")
i=0
while [[ $i -lt ${#args[@]} ]]; do
  case "${args[$i]}" in
    --tool)
      if (( i + 1 < ${#args[@]} )); then requested_tool="${args[$((i + 1))]}"; fi
      i=$((i + 2))
      ;;
    --out)
      if (( i + 1 < ${#args[@]} )); then out_dir="${args[$((i + 1))]}"; fi
      i=$((i + 2))
      ;;
    *)
      i=$((i + 1))
      ;;
  esac
done

# The installer refresh path is exactly: convert.sh --tool <tool>. Intercept only
# that shape. Every other invocation is delegated untouched so help, errors,
# --out benchmarks, full/all builds and parallel behavior stay in the engine.
if [[ $# -eq 2 && "$1" == "--tool" && "$2" != "all" ]]; then
  requested="$2"
  valid=false
  for candidate in "${CONVERTED_TOOLS[@]}"; do
    if [[ "$candidate" == "$requested" ]]; then valid=true; break; fi
  done
  if $valid; then
    exec python3 "$STATE" sync "$requested"
  fi
fi

bash "$ENGINE" "$@"

if [[ "$requested_tool" == "all" || "$requested_tool" == "aider" ]]; then
  write_aider_index "$out_dir"
  echo "[OK]  Rewrote integrations/aider/CONVENTIONS.md as an index"
fi
